# Generated by Django 3.0.4 on 2020-09-04 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='api key')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='published at'),
        ),
    ]
