# Generated by Django 3.0.4 on 2020-09-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200904_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubekeys',
            name='quote_reached',
            field=models.BooleanField(default=False, verbose_name='api quota reached'),
        ),
    ]
