# Generated by Django 3.0.4 on 2020-09-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_youtubekeys_quote_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='video title'),
        ),
    ]
